include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    todo: ignore
    invalid_annotation_target: ignore
  exclude:
    - lib/generated
    - lib/l10n
    - lib/generated_plugin_registrant.dart
    - "**/*.g.dart"
    - "**/*.freezed.dart"
linter:
  rules:
    - camel_case_types
    - camel_case_extensions
    - library_names
    - file_names
    - library_prefixes
    - curly_braces_in_flow_control_structures
    - non_constant_identifier_names
    - constant_identifier_names
    - directives_ordering
    - slash_for_doc_comments
    - package_api_docs
    - implementation_imports
    - avoid_relative_lib_imports
    - prefer_relative_imports
    - prefer_adjacent_string_concatenation
    - unnecessary_brace_in_string_interps # avoid
    - prefer_iterable_whereType
    - unnecessary_lambdas
    - avoid_init_to_null
    - unnecessary_this
    - prefer_initializing_formals
    - type_init_formals
    - empty_constructor_bodies
    - unnecessary_new
    - unnecessary_const
    - avoid_catching_errors
    - use_rethrow_when_possible
    - prefer_interpolation_to_compose_strings
    - prefer_collection_literals
    - prefer_function_declarations_over_variables
    - use_to_and_as_if_applicable
    - prefer_final_fields
    - avoid_private_typedef_functions
    - hash_and_equals
    - avoid_null_checks_in_equality_operators
    - prefer_mixin
    - type_annotate_public_apis
    - prefer_generic_function_type_aliases

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else