name: alist_app
description: alist phone and desktop application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dd_js_util: ^6.1.9
  dio: ^5.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  responsive_builder: ^0.7.0
  get_it: ^7.6.7
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  connectivity_plus: ^6.0.1
  async: ^2.11.0
  logger: ^2.1.0
  hooks_riverpod: ^2.5.1
  fast_immutable_collections: ^10.2.1
  waterfall_flow: ^3.0.3
  flutter_animate: ^4.5.0
  dd_check_plugin: ^3.1.7
  flutter_svg: ^2.0.10+1
  json_serializable: ^6.7.1
  flex_color_scheme: ^7.3.1
  flutter_markdown: ^0.6.22
  flutter_widget_from_html: ^0.14.11
  flutter_smart_dialog: ^4.9.6
  isar: ^3.1.0+1
  url_launcher: ^6.2.5
  copy_with_extension: ^5.0.4
  path_provider: ^2.1.2
  file_selector: ^1.0.3
  flutter_slidable: ^3.1.0
  isar_flutter_libs: ^3.1.0+1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  intl: ^0.19.0
  file_picker: ^8.0.0+1
  go_router: ^13.2.2
  loading_more_list_fast: ^7.1.3
  loading_more_list_library_fast: ^4.1.2
  shared_preferences: ^2.2.2
  loader_plus: ^2.0.4
  configurable_expansion_tile_null_safety: ^3.3.2
  uuid: ^4.3.3
  collection: ^1.18.0
  line_icons: ^2.0.3
  permission_handler: ^11.3.1
  path: ^1.9.0
  roundcheckbox: ^2.0.5
  colored_print: ^1.0.0
  package_info_plus: ^6.0.0
  version: ^3.0.2
  fbroadcast_nullsafety: ^4.0.4
  provider: ^6.1.2
  animated_text_kit: ^4.2.2
  chinese_font_library: ^1.1.0
  video_player: ^2.8.3

dev_dependencies:
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  freezed: ^2.4.7
  hive_generator_plus: ^3.0.4
  isar_generator: ^3.1.0+1
  copy_with_extension_gen: ^5.0.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  go_router_builder: ^2.4.1
  build_verify: ^3.1.0

dependency_overrides:
  package_info_plus: ^6.0.0
  analyzer: ^6.4.1
  meta: ^1.12.0
  uuid: ^4.3.3
  intl: ^0.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/icons/

